# Generated by Django 2.1 on 2018-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180904_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='email'),
        ),
    ]
