# Generated by Django 2.1 on 2018-09-14 08:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180904_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.photo_upload_to),
        ),
    ]
