
from enum import Enum


class ValidationStatusCode(Enum):
    PHONE_NUMBER_IS_INVALID = 111
    PASSWORD_IS_INVALID = 112
    EMAIL_ADDRESS_IS_EMPTY = 113
    EMAIL_ADDRESS_IS_INVALID = 114
    FULL_NAME_IS_EMPTY = 115
    USER_ID_IS_INVALID = 116
    NEW_PASSWORD_IS_INVALID = 117
    TRANSACTION_ID_IS_EMPTY = 118
    BEGIN_LATITUDE_IS_EMPTY = 119
    BEGIN_LONGITUDE_IS_EMPTY = 120
    BEGIN_DATE_IS_EMPTY = 121
    END_LATITUDE_IS_EMPTY = 122
    END_LONGITUDE_IS_EMPTY = 123
    END_DATE_IS_EMPTY = 124
    BUCKET_BILLING_COUNTER_IS_EMPTY = 125
    TRACKING_DOES_NOT_EXIST = 126
    PING_DOES_NOT_EXIST = 127
    PRODUCT_ID_IS_EMPTY = 128
    PURCHASE_TOKEN_IS_EMPTY = 129
    PURCHASE_TIME_IS_EMPTY = 130
    NUMBER_OF_REPORTS_IS_EMPTY = 132
    USER_PURCHASE_ID_DOES_NOT_EXIST = 133
    NOT_FOUND = 134
    ORDER_ID_IS_INVALID = 135
    PRODUCT_NAME_IS_NOT_EMPTY = 136
    PRODUCT_TYPE_IS_NOT_EMPTY = 137
    PRODUCT_TYPE_IS_DUPLICATED = 138
    THIS_PRODUCT_DOES_NOT_EXIST = 139
    YOUR_ACCOUNT_BALANCE_IS_ZERO = 140
    USER_IS_NOT_FOUND = 141
    SOMETHING_WRONG_ON_SERVER = 142
    PRICE_IS_EMPTY = 143
    PACKAGE_NAME_IS_EMPTY = 145
    SIGNED_DATA_IS_EMPTY = 146
    SIGNATURE_IS_EMPTY = 147
    PURCHASE_IS_INVALID = 148
    OLD_PASSWORD_IS_INVALID = 199