# Generated by Django 2.1 on 2018-08-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180831_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'question'},
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
