# Generated by Django 2.1 on 2018-08-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180831_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': 'choice'},
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choice',
        ),
    ]
