# Generated by Django 2.1 on 2018-09-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180906_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'questions'},
        ),
    ]
