# Generated by Django 2.1 on 2018-09-06 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('content', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('time', models.IntegerField(blank=True, default=0, null=True)),
                ('begin_date', models.DateTimeField(verbose_name='Begin Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ijobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'iJobs',
                'db_table': 'ijobs',
            },
        ),
    ]
