# Generated by Django 2.1 on 2018-09-06 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ijobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ijob',
            options={'verbose_name_plural': 'IJobs'},
        ),
    ]
