# Generated by Django 2.1 on 2018-09-07 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ijobs', '0003_auto_20180907_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ijob',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
